#!/bin/bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

export PIPELINE=${1:-cf-networking-helpers}
export TARGET=net

fly -t "${TARGET}" sync
fly -t "${TARGET}" status || fly -t "${TARGET}" login -b

fly \
  --target $TARGET \
  set-pipeline \
  --pipeline "${PIPELINE}" \
  --config "${DIR}/pipeline.yml"
